[package]
name = "rgbfusion"
version = "0.1.0"
description = "RGB Fusion 2 CLI tool"
authors = ["Christian Duerr <contact@christianduerr.com>"]
repository = "https://github.com/chrisduerr/rgbfusion.git"
license = "GPL-3.0+"
readme = "README.md"
edition = "2018"

[dependencies]
hidapi = "1.2.2"
